In [37]:
import pandas as pd
import numpy as np
import pymysql

In [38]:
db = pymysql.Connect(host='localhost', user='root', password='0226', database='customer',charset='utf8')
cursor = db.cursor()

In [39]:
sql = "SELECT * FROM new_table"
cursor.execute(sql)

pro = cursor.fetchall()
pro = pd.DataFrame(pro)
db.close()

In [40]:
pro

0   1   2    3    4   5
0    1111  여자  20   정육   간식   술
1    1112  여자  10   오일  샐러드  음료
2    1113  남자  10   과일   반찬  음료
3    1114  여자  50   음료  해산물  반찬
4    1115  여자  10   간식   채소  과일
..    ...  ..  ..  ...  ...  ..
295  1406  여자  20    국    쌀  반찬
296  1407  여자  10   계란    면  채소
297  1408  여자  50  샐러드   음료  과일
298  1409  여자  10   오일  샐러드  음료
299  1410  여자  50    국    쌀  반찬

[300 rows x 6 columns]

In [41]:
pro.columns = ['ID', 'gender', 'age', 'Rec_vi_pr_1', 'Rec_vi_pr_2', 'Rec_vi_pr_3']

In [42]:
pro_id = pro["ID"].iloc[-1]

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
le = LabelEncoder()
pro['gender'] = le.fit_transform(pro['gender'])

In [45]:
pro

ID  gender  age Rec_vi_pr_1 Rec_vi_pr_2 Rec_vi_pr_3
0    1111       1   20          정육          간식           술
1    1112       1   10          오일         샐러드          음료
2    1113       0   10          과일          반찬          음료
3    1114       1   50          음료         해산물          반찬
4    1115       1   10          간식          채소          과일
..    ...     ...  ...         ...         ...         ...
295  1406       1   20           국           쌀          반찬
296  1407       1   10          계란           면          채소
297  1408       1   50         샐러드          음료          과일
298  1409       1   10          오일         샐러드          음료
299  1410       1   50           국           쌀          반찬

[300 rows x 6 columns]

In [46]:
pro['Rec_vi_pr_1'].replace({
    '국': 0, '면': 1, '샐러드': 2, '정육' : 3, '계란' : 4, '오일' : 5, '반찬' : 6, '메인요리' : 7,
'술' : 8, '음료' : 9, '과일' : 10, '채소' : 11, '간식' : 12, '쌀' : 13, '해산물' : 14}, inplace = True)

In [47]:
pro['Rec_vi_pr_2'].replace({
    '국': 0, '면': 1, '샐러드': 2, '정육' : 3, '계란' : 4, '오일' : 5, '반찬' : 6, '메인요리' : 7,
'술' : 8, '음료' : 9, '과일' : 10, '채소' : 11, '간식' : 12, '쌀' : 13, '해산물' : 14}, inplace = True)

In [48]:
pro['Rec_vi_pr_3'].replace({
    '국': 0, '면': 1, '샐러드': 2, '정육' : 3, '계란' : 4, '오일' : 5, '반찬' : 6, '메인요리' : 7,
'술' : 8, '음료' : 9, '과일' : 10, '채소' : 11, '간식' : 12, '쌀' : 13, '해산물' : 14}, inplace = True)

In [49]:
pro = pro.fillna(0)
pro

ID  gender  age  Rec_vi_pr_1  Rec_vi_pr_2  Rec_vi_pr_3
0    1111       1   20            3           12            8
1    1112       1   10            5            2            9
2    1113       0   10           10            6            9
3    1114       1   50            9           14            6
4    1115       1   10           12           11           10
..    ...     ...  ...          ...          ...          ...
295  1406       1   20            0           13            6
296  1407       1   10            4            1           11
297  1408       1   50            2            9           10
298  1409       1   10            5            2            9
299  1410       1   50            0           13            6

[300 rows x 6 columns]

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(pro[['gender', 'age', 'Rec_vi_pr_1','Rec_vi_pr_2',]],\
                                                    pro['Rec_vi_pr_3'],test_size = 0.2, random_state =42, shuffle = False)

In [52]:
from xgboost import XGBClassifier

# 모델 선언 예시
model = XGBClassifier(n_estimators=500, learning_rate=0.2, max_depth=4, random_state = 32)

In [53]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
print(X_train)
print(X_test)

[[ 0.91986621 -0.7515432  -1.0354923   1.07022318]
 [ 0.91986621 -1.39115444 -0.52571148 -1.17500028]
 [-1.08711461 -1.39115444  0.74874059 -0.27691089]
 [ 0.91986621  1.1672905   0.49385018  1.51926787]
 [ 0.91986621 -1.39115444  1.25852142  0.84570084]
 [ 0.91986621  1.1672905   0.23895976 -0.05238855]
 [-1.08711461  1.1672905  -1.0354923  -1.17500028]
 [ 0.91986621 -1.39115444  1.25852142  0.62117849]
 [-1.08711461  0.52767927 -0.27082106 -0.50143324]
 [-1.08711461 -0.7515432  -0.78060189  0.84570084]
 [ 0.91986621  1.1672905   1.003631   -0.95047793]
 [ 0.91986621  0.52767927 -1.54527313  0.62117849]
 [-1.08711461  1.1672905   0.49385018  0.1721338 ]
 [-1.08711461 -0.7515432   0.23895976 -1.62404497]
 [ 0.91986621 -0.7515432  -1.80016354  1.29474553]
 [-1.08711461 -0.7515432  -0.27082106 -0.50143324]
 [-1.08711461  1.1672905  -0.01593065  0.1721338 ]
 [-1.08711461  1.1672905  -0.01593065  0.1721338 ]
 [ 0.91986621 -1.39115444 -0.78060189 -1.39952262]
 [-1.08711461 -0.7515432   0.23

In [54]:
model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.2, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=4, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=500,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=32, reg_alpha=0, ...)

In [34]:
y_pred = model.predict(X_test)
print(model.score(X_train,y_train))

0.9916666666666667


In [35]:
result = pd.DataFrame({'pred' : y_pred, 'real' : y_test})
result

pred  real
240     9     9
241    13    13
242     0     0
243     9     9
244     1     1
245     5     5
246     3     3
247     9     9
248     7     7
249     8     8
250     7     7
251     7     7
252    12    12
253     9     9
254    12    12
255    11    11
256    12    12
257     6     6
258     9     9
259    13    13
260     3     3
261     8     8
262     6     6
263    12    12
264     9     9
265     4     4
266    10    10
267     3     3
268     7     7
269    10    10
270     9     9
271     4     4
272     0     0
273     0     0
274     2     2
275     9     9
276    13    13
277    10    10
278     9     9
279    10    10
280     9     9
281     9     9
282     2     2
283    13    13
284    12    12
285     9     9
286    14    14
287    14    14
288     2     2
289    13    13
290     9     9
291     9     9
292     6     6
293    14     6
294     9     9
295     6     6
296    11    11
297    10    10
298     9     9
299     6     6

In [36]:
result['pred'].replace({
    0: '국', 1: '면', 2 : '샐러드', 3 : '정육', 4 : '계란', 5 : '오일', 6 :'반찬', 7 : '메인요리',
8 :'술',9 : '음료',10 : '과일',11 : '채소',12 : '간식',13 : '쌀',14 : '해산물'}, inplace = True)

In [37]:
recommand = result["pred"].iloc[-1]
recommand

'반찬'

In [ ]:
db = pymysql.Connect(host='localhost', user='root', password='0226', database='customer')
cursor = db.cursor()

query = "update user_table set Rec_vi_pr_3 = %s where ID = %s;"
data = (recommand)
cursor.execute(query, (data, pro_id))

db.commit()